version: "3"
volumes:
  bundle_cache:
  # Mount volume with default driver
services:
  db:
    image: postgres:11
    container_name: jarvis-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: jarvis
      POSTGRES_DB: jarvis_dev
    ports:
      - 8080:8080
  app:
    tty: true
    stdin_open: true
    build: .
    container_name: jarvis-app
    command: bin/rails s -b 0.0.0.0
    volumes:
      - bundle_cache:/bundle
      - .:/jarvis:cached
      - /jarvis/docker/
    ports:
      - 3000:3000
    depends_on:
      - db
      - mailcatcher
    environment:
      RAILS_ENV: development
  mailcatcher:
    image: schickling/mailcatcher
    container_name: jarvis-mail
    ports:
      - 1080:1080
      - 1025:1025